### ISSUE TITLE
Format of UMI sequence in header

### ISSUE THREAD

**Issue by HyunjunNam** [claretbio/SRSLYumi#3]
Hello,

I'm testing SRSLYumi tool for eWES assay which is using SRSLY chemistry with 10bp i7/i5 index.

I got the UMI sequence in the header by using the command (srslyumi --index-bp 10 [rundirectory] [outputdirectory])  like below,

@A00903:861:HJN3YDMXY:1:1101:15103:1000:**CACCTATTT+AGTCGGGAA** 1:N:0:TGCGAAGTGA+NATCTGCAGT

I expected I will got  just the 9bp UMI sequence, but I had 9bp+9bp UMI sequence.

Is this the correct and expected result?
Please let me know if you see anything incorrect.

Thank you,
Hyunjun

**Comment by cschwart** [comment]
Hi Hyunjun,

Yes this is the appropriate result. bcl2fastq's TrimUMI option puts the 9bp UMI with the first 9 bases of read 2. So in this case, `CACCTATTT` is the UMI and `AGTCGGGAA` is the start of read 2.

Best,
Camille
